name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_SERVER_USER }}
          password: ${{ secrets.HOST_SERVER_PASSWORD }}
          port: ${{ secrets.HOST_SERVER_PORT }}
          script: |
            cd ${{ secrets.HOST_SERVER_FE_PATH }}
            source ~/.zshrc
            npm link @angular/cli
            git pull
            ng b --configuration=production
            git add .
            git commit -m 'master production package'
            git push
            echo 'Task completed'
